apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devops-platform-db
spec:
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      storageClassName: "gp2" # Change to your storage class (gp2 for AWS, standard for GCP, etc.)