# Docker Compose for external database deployment
version: '3.8'

services:
  # Main Application Service (External Database Mode)
  app:
    build: .
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_MODE: external
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      # GitHub integration (optional)
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}
      # External database connection details
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: ${DB_SSL:-true}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-false}
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

  # Database Migration Service for External DB
  migrate:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_MODE: external
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: ${DB_SSL:-true}
    command: npm run db:push
    restart: "no"