apiVersion: batch/v1
kind: Job
metadata:
  name: devops-platform-migrate
  labels:
    app: devops-platform
    component: migration
spec:
  template:
    metadata:
      labels:
        app: devops-platform
        component: migration
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: devops-platform:latest
        command: ["npm", "run", "db:push"]
        env:
        - name: NODE_ENV
          value: "production"
        envFrom:
        - configMapRef:
            name: devops-platform-config
        - secretRef:
            name: devops-platform-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
  backoffLimit: 4